# Generated by Django 5.1.2 on 2024-11-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_journalexpense'),
        ('vendor', '0002_alter_vendor_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_expenses', to='vendor.vendor'),
        ),
    ]
