# Generated by Django 5.1.2 on 2024-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_source',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash in Hand'), ('ACC', 'Account'), ('CLIENT', 'Client Provided'), ('LOAN', 'Project Loan')], max_length=6, null=True),
        ),
    ]
