# Generated by Django 5.1.2 on 2024-11-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_alter_expense_budget_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('UNPAID', 'Unpaid')], default='UNPAID', max_length=6),
        ),
    ]
