# Generated by Django 5.1.2 on 2024-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0006_expense_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='budget_source',
            field=models.CharField(blank=True, choices=[('CASH', 'Cash in Hand'), ('ACC', 'Account')], max_length=6, null=True),
        ),
    ]
