# Generated by Django 5.1.2 on 2024-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Account funds assigned to the project', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='project_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cash in hand assigned to the project', max_digits=12),
        ),
        migrations.AddField(
            model_name='project',
            name='project_client_fund',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Client funds assigned to the project', max_digits=12),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_budget',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total project budget', max_digits=12),
        ),
    ]
