# Generated by Django 5.1.2 on 2024-11-06 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_project_account_balance_project_project_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the lender', max_length=255)),
                ('contact_info', models.TextField(blank=True, help_text='Contact information for the lender', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Total loan amount', max_digits=12)),
                ('date_issued', models.DateField(default=django.utils.timezone.now, help_text='Date when the loan was issued')),
                ('is_repaid', models.BooleanField(default=False, help_text='Indicates if the loan has been fully repaid')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='project.lender')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='project.project')),
            ],
        ),
    ]
