# Generated by Django 5.1.2 on 2024-11-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_lender_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='lender',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number of the lender', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='bic',
            field=models.CharField(blank=True, help_text='BIC of the lender', max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='iban',
            field=models.CharField(blank=True, help_text='IBAN of the lender', max_length=34, null=True),
        ),
    ]
