# Generated by Django 5.1.2 on 2024-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_lender_account_number_lender_bic_lender_iban'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='lender',
            name='iban',
        ),
        migrations.AddField(
            model_name='lender',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address of the lender', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='lender',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number of the lender', max_length=20, null=True),
        ),
    ]
