# Generated by Django 5.1.2 on 2024-11-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_project_project_loan_recieved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('DF', 'Draft'), ('QT', 'Quotation'), ('AW', 'Awaiting Approval'), ('CL', 'Cancelled'), ('IP', 'In Progress'), ('FN', 'Finished')], default='QT', help_text='Current status of the project', max_length=2),
        ),
    ]
