# Generated by Django 5.1.2 on 2024-11-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('DF', 'Draft'), ('AW', 'Awaiting Quote Approval'), ('CL', 'Cancelled'), ('IP', 'In Progress'), ('FN', 'Finished')], default='DF', help_text='Current status of the project', max_length=2),
        ),
    ]
