# Generated by Django 5.1.2 on 2024-11-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_total_budget_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget_source',
            field=models.CharField(choices=[('CASH', 'Cash in Hand'), ('ACC', 'Account')], default='CASH', help_text='Source of the project budget', max_length=6),
        ),
    ]
