# Generated by Django 5.1.2 on 2024-11-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalExpense',
        ),
    ]
