# Generated by Django 5.1.2 on 2024-11-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_accountbalance_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbalance',
            name='starting_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
