# Generated by Django 5.1.2 on 2024-11-25 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 25, 21, 18, 13, 942314, tzinfo=datetime.timezone.utc)),
        ),
    ]
