# Generated by Django 5.1.2 on 2024-11-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
