# Generated by Django 5.1.2 on 2024-11-26 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 26, 1, 37, 51, 909012, tzinfo=datetime.timezone.utc)),
        ),
    ]
