# Generated by Django 5.1.2 on 2024-11-13 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoice_project'),
        ('project', '0012_project_total_budget_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='project.project'),
        ),
    ]
