# Generated by Django 5.1.2 on 2024-11-28 00:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 0, 24, 3, 773366, tzinfo=datetime.timezone.utc)),
        ),
    ]
