# Generated by Django 5.1.2 on 2024-11-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='percent_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
