# Generated by Django 5.1.2 on 2024-11-28 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2024, 11, 28, 8, 4, 42, 245521, tzinfo=datetime.timezone.utc)),
        ),
    ]
