# Generated by Django 5.1.2 on 2024-11-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
