# Generated by Django 5.1.2 on 2024-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0009_alter_invoice_phone_alter_invoiceitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
