# Generated by Django 5.1.2 on 2024-12-13 02:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0011_alter_invoiceitem_tax"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, region=None
            ),
        ),
    ]
