# Generated by Django 5.1.2 on 2024-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0012_alter_invoice_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email",
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
