# Generated by Django 5.1.2 on 2024-11-06 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('quotation_number', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=15)),
                ('total_in_words', models.CharField(blank=True, editable=False, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotation.quotation')),
            ],
        ),
    ]
