# Generated by Django 5.1.2 on 2024-11-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_project_status'),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotation',
            old_name='location',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='text',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_in_words',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='website_link',
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='project',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotation', to='project.project'),
            preserve_default=False,
        ),
    ]
