# Generated by Django 5.1.2 on 2024-11-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_rename_location_quotation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_in_words',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
