# Generated by Django 5.1.2 on 2024-11-07 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_quotation_total_amount_quotation_total_in_words'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
