# Generated by Django 5.1.2 on 2024-11-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_alter_quotationitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
