# Generated by Django 5.1.2 on 2024-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_quotationitem_percent_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitem',
            name='percent_tax',
        ),
        migrations.AddField(
            model_name='quotation',
            name='percent_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
