# Generated by Django 5.1.2 on 2024-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0009_alter_quotation_percent_tax_alter_quotation_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
