# Generated by Django 5.1.2 on 2024-12-13 02:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_remove_project_client_funds_received_and_more"),
        (
            "quotation",
            "0012_alter_quotation_options_remove_quotation_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quotation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="quotation",
            name="percent_tax",
        ),
        migrations.AddField(
            model_name="quotation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="quotation",
            name="letterhead",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="quotation",
            name="tax",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="quotationitem",
            name="tax",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(50.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, region=None
            ),
        ),
        migrations.AlterField(
            model_name="quotation",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotations",
                to="project.project",
            ),
        ),
    ]
