# Generated by Django 5.1.2 on 2024-12-13 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0014_remove_project_client_funds_received_and_more"),
        (
            "quotation",
            "0013_alter_quotation_options_remove_quotation_percent_tax_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="project",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="project.project"
            ),
        ),
    ]
