# Generated by Django 5.1.2 on 2024-12-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0016_alter_quotation_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="email",
            field=models.EmailField(max_length=50),
        ),
    ]
