# Generated by Django 5.1.2 on 2024-12-14 09:12

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotation", "0017_alter_quotation_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quotation",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, region="PK"
            ),
        ),
    ]
