# Generated by Django 5.1.2 on 2024-11-07 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanreturn',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='loanreturn',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanreturn',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
