# Generated by Django 5.1.2 on 2024-11-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, help_text='Interest rate', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payable_after_interest',
            field=models.DecimalField(decimal_places=2, help_text='Payable after interest', max_digits=12, null=True),
        ),
    ]
