# Generated by Django 5.1.2 on 2024-11-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_alter_loanreturn_remarks_and_more'),
        ('project', '0013_alter_project_budget_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='project.project'),
        ),
    ]
