# Generated by Django 5.1.2 on 2024-11-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='reason',
            field=models.CharField(blank=True, max_length=544, null=True),
        ),
    ]
