# Generated by Django 5.1.2 on 2024-11-29 10:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_loan_interest_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanreturn',
            name='source',
        ),
        migrations.CreateModel(
            name='MiscLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, help_text='Total loan amount', max_digits=12)),
                ('payable_after_interest', models.DecimalField(decimal_places=2, help_text='Payable after interest', max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate as a percentage', max_digits=5, null=True)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining loan balance', max_digits=12)),
                ('date_issued', models.DateField(default=django.utils.timezone.now, help_text='Date when the loan was issued')),
                ('due_date', models.DateField(help_text='Due date for loan repayment')),
                ('is_repaid', models.BooleanField(default=False, help_text='Indicates if the loan has been fully repaid')),
                ('reason', models.CharField(blank=True, max_length=544, null=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misc_loans', to='loan.lender')),
            ],
        ),
    ]
