# Generated by Django 5.1.3 on 2024-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_remove_loanreturn_source_miscloan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Phone number of the lender', max_length=20, null=True),
        ),
    ]
