# Generated by Django 5.1.2 on 2024-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_lender_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='phone',
            field=models.IntegerField(blank=True, help_text='Phone number of the lender', null=True),
        ),
    ]
