# Generated by Django 5.1.2 on 2024-12-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_lender_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lender',
            name='bic',
        ),
        migrations.AddField(
            model_name='lender',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Bank Account of the lender', max_length=11, null=True),
        ),
    ]
