# Generated by Django 5.1.2 on 2024-10-29 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='remarks',
        ),
    ]
