# Generated by Django 5.1.2 on 2024-10-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tax'),
        ('customer', '0002_remove_customer_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_due_period',
            field=models.CharField(choices=[('net_15', 'Net 15'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('due_receipt', 'Due On Receipt'), ('due_eom', 'Due End of Month')], default='due_receipt', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='core.tax'),
        ),
    ]
