# Generated by Django 5.1.2 on 2024-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_company_id_customer_payment_due_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='payment_due_period',
            field=models.CharField(choices=[('net_15', 'Net 15'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('due_receipt', 'Due On Receipt'), ('due_eom', 'Due End of Month')], default='due_eom', max_length=15),
        ),
    ]
