# Generated by Django 5.1.3 on 2024-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='work_phone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_phone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
