# Generated by Django 5.1.2 on 2024-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_contactperson_work_phone_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='work_phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='work_phone',
            field=models.IntegerField(blank=True),
        ),
    ]
