# Generated by Django 5.1.3 on 2024-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_contactperson_work_phone_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='tax',
        ),
        migrations.DeleteModel(
            name='ContactPerson',
        ),
    ]
