# Generated by Django 5.1.2 on 2024-12-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_remove_customer_tax_delete_contactperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='work_phone',
        ),
    ]
