# Generated by Django 5.1.2 on 2024-12-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_remove_customer_mobile_remove_customer_work_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
