# Generated by Django 5.1.2 on 2024-12-12 21:05

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_customer_mobile_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="mobile",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=15, region=None
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=15, null=True, region=None
            ),
        ),
    ]
