# Generated by Django 5.1.2 on 2024-12-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_alter_customer_mobile_alter_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="other_details",
        ),
        migrations.AlterField(
            model_name="customer",
            name="company_name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="customer",
            name="first_name",
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=18),
        ),
    ]
