# Generated by Django 5.1.2 on 2024-11-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
