# Generated by Django 5.1.2 on 2024-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_ledger_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('BUDGET_ASSIGN', 'Budget Assigned to Project'), ('TRANSFER', 'Funds Transfer'), ('CREATE_LOAN', 'Loan Created'), ('RETURN_LOAN', 'Loan Returned')], max_length=50),
        ),
    ]
