# Generated by Django 5.1.2 on 2024-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_alter_ledger_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('BUDGET_ASSIGN', 'Budget Assigned to Project'), ('TRANSFER', 'Funds Transfer'), ('CREATE_LOAN', 'Loan Created'), ('RETURN_LOAN', 'Loan Returned'), ('MISC_LOAN_CREATE', 'Miscellaneous Loan'), ('MISC_LOAN_RETURN', 'Miscellaneous Loan Return'), ('CREATE_EXPENSE', 'Expense Created'), ('MISC_EXPENSE', 'Journal Expense Created'), ('ADD_CASH', 'Added Cash'), ('INVOICE_PAYMENT', 'Invoice Paid'), ('ADD_ACC_BALANCE', 'Invoice Paid')], max_length=50),
        ),
    ]
