# Generated by Django 5.1.2 on 2024-12-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0010_alter_ledger_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledger",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
