# Generated by Django 5.1.2 on 2024-11-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashinhand',
            name='name',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
