# Generated by Django 5.1.2 on 2024-11-08 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cashinhand_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.DeleteModel(
            name='CashInHand',
        ),
    ]
