# Generated by Django 5.1.2 on 2024-11-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_delete_accountbalance_delete_cashinhand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
