# Generated by Django 5.1.2 on 2024-11-30 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
