# Generated by Django 5.1.3 on 2024-12-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.IntegerField(blank=True, max_length=15),
        ),
    ]
