# Generated by Django 5.1.2 on 2024-12-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_billingaddress_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone',
            field=models.IntegerField(blank=True),
        ),
    ]
