# Generated by Django 5.1.3 on 2024-12-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_billingaddress_phone'),
        ('customer', '0009_remove_customer_tax_delete_contactperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
